### ISSUE TITLE
UART_GET Request for InfoMem contents does not return expected data

### ISSUE THREAD

**Issue by lumagi** [ShimmerResearch/shimmer3#8]
The UART interface of the Shimmer provides a request to read InfoMem contents, i.e. UART_PROP_INFOMEM. However, the request can fail in some cases and only returns data previously contained in the send buffer instead of the requested memory bytes. This issue occurs both with the SDLog v0.19.0 and the LogAndStream v0.11.0 firmware versions.

The bug is likely caused by a bug in the firmware. In the following code locations, the memcpy operation that is responsible for transferring the requested memory into the send buffer is protected by an if clause which checks the available size. However, the variable that is used to perform the check is not initialized as part of the request and hence contains an undefined value that only triggers the issue under some conditions.

Code locations:
* LogAndStream: [main.c](https://github.com/ShimmerResearch/shimmer3/blob/04d8e21e21c4be8b58596cfc57d9eb5f5f7d68c5/LogAndStream/main.c#L8526)
* SDLog: [main.c](https://github.com/ShimmerResearch/shimmer3/blob/04d8e21e21c4be8b58596cfc57d9eb5f5f7d68c5/SDLog/main.c#L3573)

At these locations, the check is performed against the variable `uartDcMemLength` which is however not set as part of the request.

Steps to reproduce:
* Send a request with the following parameters to set `uartDcMemLength` to a value of 0xFF:
    * `UART_GET`, `UART_COMP_DAUGHTER_CARD`, `UART_PROP_CARD_ID`
    * Request Parameters: Length 0xFF, Offset 0x0
* Send the actual request to trigger the bug:
    * `UART_GET`, `UART_COMP_SHIMMER`, `UART_PROP_INFOMEM`
    * Request Parameters: Length 0xC, Offset 0xC7 (Read the current experiment name)

**Comment by marknolan** [comment]
Hi Lumagi,

It looks like you are correct. That being said, we've only ever used that command to read all of the InfoMem (i.e., trial configuration) rather then reading specific parameters from it. I think that's why it's never been an issue for us. We designed the command itself to have flexibility for future development (i.e., by adding in offset + length parameters) but it was never needed. 

The InfoMem in the MSP430 is divided into 4 memory locations D, C, B and A - each of which is 128 bytes long. In Consensys we loop through and read in one, 128 bytes at a time. Would would you application to read the full 128 byte chunks?

**Comment by lumagi** [comment]
I believe that reading a larger chunk of data would not mitigate the issue since it does not affect the value of the `uartDcMemLength`  variable. The bug does not always occur since it depends on the value of the memory location that the variable resides in. I currently use a workaround in the pyshimmer API where I first send a different request to initialize the `uartDcMemLength` variable to the required value and then perform the actual request.
To fix the underlying issue in the firmware, I submitted pull request #9 .

**Comment by marknolan** [comment]
Thanks Lumagi for identifying the issue and for the suggested fix, this will feature in the next firmware release.
